### ISSUE TITLE
Subscription not working

### ISSUE THREAD

**Issue by DavidM974** [PaylineByMonext/payline-prestashop#2]
Hello,
i'm testing the subscription mode in test and i have an error when i finish the transaction. It comeback to mydashboard with the message "Can't create the subscription" i don't know if there is some configuration to create a subcription in test mode ?
Can you help me?

**Comment by DavidM974** [comment]
79201994443303

**Comment by PaylineGitHub** [comment]
Indeed an option was missing. It's now activated, all should be fine. I'll tell you more through support@payline.com
